version: '2.0'
services:
  international-waste-shipments-training-database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "international-waste-shipments-training-database"
    env_file: config.env
    ports:
      - "5432:5432"
    
    user: postgres
    networks:
      - docker_database
    
networks:
  docker_database:
    driver: bridge
