
#!/bin/bash

if [ ${IWS_POSTGRES_CREATE_TABLESPACE_DIRECTORIES,,} = "true" ]; then
  mkdir -p ${IWS_POSTGRES_TABLES_TABLESPACE_LOCATION} && mkdir -p ${IWS_POSTGRES_INDEXES_TABLESPACE_LOCATION}
  chmod -R 700 ${IWS_POSTGRES_TABLES_TABLESPACE_LOCATION} && chmod -R 700 ${IWS_POSTGRES_INDEXES_TABLESPACE_LOCATION}  
fi

psql -c "CREATE USER ${IWS_POSTGRES_IWS_USER} WITH PASSWORD '${IWS_POSTGRES_IWS_PASSWORD}' NOSUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;"
psql -c "CREATE DATABASE iws WITH OWNER = ${IWS_POSTGRES_IWS_USER};"
psql -c "GRANT ALL PRIVILEGES ON DATABASE iws TO ${IWS_POSTGRES_IWS_USER};"
psql -d iws -c "CREATE SCHEMA ${IWS_POSTGRES_IWS_SCHEMA} AUTHORIZATION ${IWS_POSTGRES_IWS_USER};"
psql -c "CREATE TABLESPACE ${IWS_POSTGRES_TABLES_TABLESPACE} OWNER ${IWS_POSTGRES_IWS_USER} LOCATION '${IWS_POSTGRES_TABLES_TABLESPACE_LOCATION}';"
psql -c "CREATE TABLESPACE ${IWS_POSTGRES_INDEXES_TABLESPACE} OWNER ${IWS_POSTGRES_IWS_USER} LOCATION '${IWS_POSTGRES_INDEXES_TABLESPACE_LOCATION}';"
